driver:
  i2c_address: 0x40
  steering_channel: 0
  throttle_channel: 1
  max_speed: 0.8
  min_speed: 0.08
  max_angle: 32.2
  min_angle: 0
  node_name: "jetracer_driver_node"

control:
  node_name: "jetracer_control_mm_node"
  pub_name: "jetracer_vels_pub"

navigation:
  node_name_img: "jetracer_img_process_node"
  node_name_obs: "jetracer_emergency_stop_node"
  node_name_obj: "jetracer_objects_node"
  pub_name_img: "jetracer_goal_point_pub"
  pub_name_obs: "jetracer_emergency_stop_pub"
  pub_name_obj: "jetracer_object_pub"
  offsetright: 190
  offsetmid: 230
  min_center: 0.31
  min_back: 0.18
  min_sides: 0.18


sensors:
  pub_name_img: "jetracer_img_pub"
  node_name_img_oak: "jetracer_img_pub_node"
  node_name_img_depth_intel: "jetracer_img_depth_pub_node"
  pub_name_depth: "jetracer_depth_pub"
  node_name_rplidar: "rplidarNode"
  pub_name_rplidar: "scan"
  srv_name: "jetracer_srv_distance"
  
rate: 10
confidence: 0.8
